### ISSUE TITLE
Add Contact - warning is too big, styling and colors not suggestive of error text

### ISSUE THREAD

**Issue by jplotz** [The-Cliff-Face/Manager_Of_Contacts#25]
When adding a contact, the entry of an invalid phone number or email will create a warning text.
![image](https://github.com/The-Cliff-Face/Manager_Of_Contacts/assets/113050852/80be128a-39b8-453f-aa21-c2fe14b3f7c6)

This is desired behavior, but it may be better to do one of the following:
1. Decrease the size of this text and change its styling to the red color that is in use for errors during login (hex #b11030). Add a light-colored background for consistency with signup.html

2. Add a warning like in [this tutorial](https://code-boxx.com/show-error-messages-html-forms/)
![image](https://github.com/The-Cliff-Face/Manager_Of_Contacts/assets/113050852/81b7517a-f8a9-40c3-811d-4276eac671bc)

**Comment by mistrynick** [comment]
let me know if the current implementation is satisfactory
