### ISSUE TITLE
(Low importance) On edit contact, ctrl+backspacing all the content in a validated field prevents user from entering input

### ISSUE THREAD

**Issue by sivadailuj** [The-Cliff-Face/Manager_Of_Contacts#30]
![image](https://github.com/The-Cliff-Face/Manager_Of_Contacts/assets/123046787/06d2bdd2-4069-4735-a89d-f94f19ad96bd)
Validation hint doesn't go away and user can no longer type in that field.

**Comment by jplotz** [comment]
I think it got fixed
